# Generated by Django 4.0.6 on 2022-07-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdetail',
            name='purpose',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
