# Generated by Django 4.0.6 on 2022-07-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_trainingdetail_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingdetail',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='trainingdetail',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
